apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: ecommerce-microservices
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: checkout
        imagePullPolicy: Always
        image: leofranzen/ecommerce-microservices-checkout:1.0.0
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalog:3550"
        - name: SHIPPING_SERVICE_ADDR
          value: "shipping:50051"
        - name: PAYMENT_SERVICE_ADDR
          value: "payment:50051"
        - name: EMAIL_SERVICE_ADDR
          value: "email:5000"
        - name: CURRENCY_SERVICE_ADDR
          value: "currency:7000"
        - name: CART_SERVICE_ADDR
          value: "cart:7070"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]          
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: ecommerce-microservices
spec:
  selector:
    app: checkout
  type: ClusterIP
  ports:
  - port: 5050
    targetPort: 5050          
