apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  namespace: ecommerce-microservices
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: email
        imagePullPolicy: Always
        image: leofranzen/ecommerce-microservices-email:1.0.0
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
---
apiVersion: v1
kind: Service
metadata:
  name: email
  namespace: ecommerce-microservices
spec:
  selector:
    app: email
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 8080
