apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad
  namespace: ecommerce-microservices
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ad
  template:
    metadata:
      labels:
        app: ad
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: ad
        imagePullPolicy: Always
        image: leofranzen/ecommerce-microservices-ad:1.0.0
        resources:
          requests:
            cpu: 50m
            memory: 90Mi
          limits:
            cpu: 100m
            memory: 150Mi
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
---
apiVersion: v1
kind: Service
metadata:
  name: ad
  namespace: ecommerce-microservices
spec:
  selector:
    app: ad
  type: ClusterIP
  ports:
  - port: 9555
    targetPort: 9555
