apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog
  namespace: ecommerce-microservices
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: productcatalog
  template:
    metadata:
      labels:
        app: productcatalog
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: productcatalog
        imagePullPolicy: Always
        image: leofranzen/ecommerce-microservices-productcatalog:1.0.0
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalog
  namespace: ecommerce-microservices
spec:
  selector:
    app: productcatalog
  type: ClusterIP
  ports:
  - port: 3550
    targetPort: 3550
