apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  namespace: ecommerce-microservices
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: recommendation
        imagePullPolicy: Always
        image: leofranzen/ecommerce-microservices-recommendation:1.0.0
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalog:3550"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation
  namespace: ecommerce-microservices
spec:
  selector:
    app: recommendation
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
